### ISSUE TITLE
python memory not freeing memory of query

### ISSUE THREAD

**Issue by AlaRuba** [versae/neo4j-rest-client#118]
Hi,

I have a Django app that uses neo4j-rest-client. I have a view that makes repeated queries in the my database like so.
gdb = GraphDatabase(graphUrl)
q = some query
result = gdb.query(q=q)

This issue https://github.com/versae/neo4j-rest-client/issues/109 seems to have do with transactions.

My query is more along the lines of "MATCH (n{handle:'"+handle+"'})-[r]-(x) RETURN r, n,x". Thus, I can't call result.commit(). That generates an error. 

However, when I leave the function, I notice the memory taken up by result is never freed even when I call del result and gc.collect(). How do I free the memory of taken up by this query? 

Thanks

**Comment by versae** [comment]
Hi,

Sorry for the delay, I was away :) Do you still have the problem? The thing is that I don't know if the problem is the `requests` library itself or `neo4jrestclient`. So, if you try to run that Django view without `neo4jrestclient` and is still not freeing the memory, then it is `requests` or something else.

```python
@profile
def get_node(handle):
    url = "http://d1rygkc2z32bg1.cloudfront.net/"
    result = requests.post('http://temporary.robobrain.me:7474/db/data/transaction/commit',
    data=json.dumps({'statements': [{
        'statement': "MATCH (n{handle:'"+handle+"'})-[r]-(x) RETURN r, n,x"}]
        }),
        headers={
            'Accept': 'application/json; charset=UTF-8',
            'Content-Type': 'application/json'
        }).json()
    result = result['results'][0]

    result = result['data']
    length = len(result)
    nodes = {}
    links = {}

    del result
    return {"nodes":nodes,"links":links}


get_node('shoe')
get_node('knife')
get_node('track')
get_node('sitting_human')
```
