### ISSUE TITLE
AttributeError calling create() on Label instance.

### ISSUE THREAD

**Issue by paolodina** [versae/neo4j-rest-client#119]
Hi, I'm [following the tutorial](https://neo4j-rest-client.readthedocs.org/en/latest/info.html#getting-started) and I wonder why I get this error:
```
>>> people = gdb.labels.create("Person")
>>> people.add(alice, bob)
>>> carl = people.create(name="Carl", age=25)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Label' object has no attribute 'create'
``` 

Python 2.7.8 and neo4j-rest-client 2.1.0 installed using pip.

This works:
```
people.add(gdb.nodes.create(name="Carl", age=25))
```

but if I understand it correctly the create() method called directly on labels was meant to avoid that.

**Comment by versae** [comment]
And you are right. Let me check that.

**Comment by versae** [comment]
I also added a [test for that](https://github.com/versae/neo4j-rest-client/commit/24d7a3448d72b621738adf6de63724d718966b54#diff-03441732a47e360aeb687663f5b03355R201) :)
