### ISSUE TITLE
Location of conf? error from gdb = GraphDatabase("http://localhost:7474/db/data/")

### ISSUE THREAD

**Issue by scheung38** [versae/neo4j-rest-client#121]
The following works in IPython console but not working run as script?
```
from neo4jrestclient.client import GraphDatabase
```
next line:
```
gdb = GraphDatabase("http://localhost:7474/db/data/")
  File "/Users/seb/anaconda/envs/pyenv2.7.10/lib/python2.7/site-packages/neo4jrestclient/request.py", line 348, in _request
    raise StatusException(401, "Authorization Required")
StatusException: Error [401]: Unauthorized. No permission -- see authorization schemes.
Authorization Required
```
In OSX, ~/.bashrc already set:
```
export NEO4J_USERNAME=neo4j
export NEO4J_PASSWORD=mypassword
```

I was in neo4jrestclient 2.1.0, then downgraded to 2.0.0 and still the same. Any idea?

**Comment by paolodina** [comment]
No idea, but as a temporary workaround you could try with
```
gdb = GraphDatabase("http://neo4j:mypassword@localhost:7474/db/data/")
```

**Comment by scheung38** [comment]
Only halfway through doc

http://py2neo.org/2.0/essentials.html

I see:

"Alternatively, authentication can be disabled completely by editing the value of the dbms.security.authorization_enabled setting in the conf/neo4j-server.properties file." But where is this conf? Where is this conf when initiating a new project, I just don't find it intuitive.

**Comment by paolodina** [comment]
For Neo4j v2.2.5 it's in `$NEO4J_HOME/conf/neo4j-server.properties` line 23. Neo home is the top-level directory where neo has been extracted.

**Comment by scheung38** [comment]
@paolodina Thanks for showing this, but this is not a good start to using neo4j as user doesn't expect to have to do this in trying out for the first time.

**Comment by paolodina** [comment]
Refer to the top-level directory where neo4j was extracted as: `NEO4J_HOME`. You should'n set this as environment variable. A way to find its value is to start neo4j server, login and click on the first link on the left. Look at Database -> Location. In Linux it could be `/home/user/devel/neo4j-community/data/graph.db`. So `NEO4J_HOME` is `/home/user/devel/neo4j-community`.

HTH

**Comment by scheung38** [comment]
@paolodina as I mentioned, I didn't use NEO4J_HOME anywhere so I am a but confused why you are asking me to refer NEO4J_HOME

**Comment by paolodina** [comment]
I guess you downloaded Neo4j package and inflated it in some directory right? Conventionally, call this directory NEO4J_HOME. At least in Linux, `conf/neo4j-server.properties` is located under that directory.

**Comment by scheung38** [comment]
@paolodina, no I used brew install neo4j commandline to install.

OK now found
```
/usr/local/Cellar/neo4j/2.2.5/libexec/conf
```

**Comment by versae** [comment]
Just some clarification, `neo4jrestclient` is an independent driver for Neo4j, and while `py2neo` was so too, its author is now working for Neo4j.

That being said, Neo4j changed authentication in 2.2 and unfortunately I haven't had the time to update `neo4jrestclient` yet.

Other than that, can I close the issue as it's actually not related to `neo4jrestclient`?

**Comment by scheung38** [comment]
from py2neo import Graph, Node, Relationship, authenticate
import os

url = os.environ.get('GRAPHENEDB_URL', 'http://localhost:7474')
username = os.environ.get('NEO4J_USERNAME')
password = os.environ.get('NEO4J_PASSWORD')

if username and password:
    authenticate(url.strip('http://'), username, password)

graph = Graph(url + '/db/data/')

buenos_aires = Node("Port", name="Buenos Aires")
new_york = Node("Port", name="New York")
liverpool = Node("Port", name="Liverpool")
casablanca = Node("Port", name="Casablanca")
cape_town = Node("Port", name="Cape Town")

graph.create(buenos_aires, new_york, liverpool, casablanca, cape_town)

rel1 = Relationship(buenos_aires, "TRIP_TO", new_york, days=6)
rel2 = Relationship(buenos_aires, "TRIP_TO", casablanca, days=5)
rel3 = Relationship(buenos_aires, "TRIP_TO", cape_town, days=4)
rel4 = Relationship(new_york, "TRIP_TO", liverpool, days=4)

graph.create(rel1, rel2, rel3, rel4)

**Comment by versae** [comment]
You can use both, there is no need to do so. You can also [execute Cypher queries](http://py2neo.org/2.0/cypher.html) in py2neo.

As for the specific queries, IMHO StackOverflow and the official Neo4j mailing list are the right places.
