### ISSUE TITLE
How would I get a node based on property, in order to create a relationship?

### ISSUE THREAD

**Issue by ahrennsiva** [versae/neo4j-rest-client#127]
Is it possible to find a node given a property, and create a relationship using that information. Code sample below, and the neo_*_* fields are populated from a separate Django model's data. The issue occurs at 

```python
from student.models import *
from neo4jrestclient.client import GraphDatabase
from neo4jrestclient import client


db = GraphDatabase("http://localhost:7474", username="neo4j", password="password")

def create_campus(campus):
    campus_set = db.labels.create("Campuses")
    campus_to_store = db.nodes.create(neo_campus_id = campus.id, neo_campusname=campus.name)
    campus_set.add(campus_to_store)

def create_student(student):
    student_set = db.labels.create("Students")
    student_to_store = db.nodes.create(
        neo_student_id=student.random_id,
        neo_name=(student.first_name + " " + student.last_name),
        neo_gender=student.gender,
        neo_ethnicity=student.ethnicity
    )
    student_set.add(student_to_store)       
    #Where error occurs 
    node_transaction_campus = db.nodes.get(neo_campus_id=student.campus.id)
    rel = db.relationships.create(student_to_store, "Attends School At", node_transaction_campus)
```

**Comment by versae** [comment]
You can use the label `Students` to do the [filtering](https://neo4j-rest-client.readthedocs.io/en/latest/labels.html#list-get-and-filter), or create a Cypher query as well.
```python
student_set.get(neo_campus_id=student.campus.id)
```

Using `Q` objects might give you more flexibility, although they are not very well tested.

```python
from neo4jrestclient.query import Q

student_set.filter(gdb.Q("neo_name", "istartswith", student.first_name))
```

**Comment by ahrennsiva** [comment]
@versae Thanks that was helpful. Upon node creation, is there a way to make sure that the node is unique by a property of the node? i know that on label creation there don't seem to be duplicates, but I am able to create multiple of the same campus or major.

**Comment by versae** [comment]
Unfortunately, `neo4jrestclient` doesn't expose the [schema constraints](https://neo4j.com/docs/developer-manual/current/cypher/#query-constraints) nicely in its API, but you can still add constrains on labels by running Cypher queries I guess.
```
CREATE CONSTRAINT ON (student:Student) ASSERT student.neo_campus_id IS UNIQUE
```

The old way was to use an index and index by the property you want to be unique with one of the two supported methods of Neo4j, `get_or_create` or `create_or_fail`.

```python
students_idx = gdb.nodes.indexes.create("Students")
students_idx.get_or_create(key="neo_campus_id", value=student.campus.id, item=student_to_store)
```

But not sure if this functionality is still alive in newer versions of Neo4j.
