### ISSUE TITLE
How can I update values of existing properties on a relationship?

### ISSUE THREAD

**Issue by ahrennsiva** [versae/neo4j-rest-client#129]
If I'm storing properties on a relationship created using something like:

rel = student_to_store.relationships.create("Attends School At", matching, neo_started_degree_year=2015, neo_ending_degree_year=2019)

How can I update those two properties later on?

**Comment by versae** [comment]
I really don't understand what `matching` is doing there, but to update properties you just need to edit the values as in a dictionary.
```python
rel["neo_started_degree_year"] = 2016
```
